server:
  port: 9000
security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    platform: h2
    url: 'jdbc:h2:mem:mouni '
  h2:
    console:
      enabled: true
  application:
    name: oauth-server
  